### ISSUE TITLE
client.connect or Ethernet.maintain() should be called every minute 

### ISSUE THREAD

**Issue by tindaio** [ntruchsess/arduino_uip#128]
Why do I need to call  Ethernet.maintain(); every minute if I will not used client.connect? 

If I will not call Ethernet.maintain() or  client.connect every minute I cannot communicate to my server.

Any ideas?

**Comment by ntruchsess** [comment]
That is how it is designed. Due to the lack of real backround-processing on a µC as an Arduino is the library is not processing anything if no method is called, so if either have to call Client/Server.available() or Ethernet.maintain() on a regular basis, otherwise the library just stalls.

If you wan't processing in the background you may decide to call Ethernet.maintain() from a timer-driven interrupt routine though.
